### ISSUE TITLE
dekstop app

### ISSUE THREAD

**Issue by ghost** [lagmoellertim/ImageShare-App#2]
you know you can now run flutter on desktop ?
so ou can reuse all the code from the mobile app for the desktop app 

Its awesome

https://github.com/google/flutter-desktop-embedding

**Comment by lagmoellertim** [comment]
Thank you for the link, but it would actually be more difficult to port the python desktop app to flutter than just to maintain the python version, since basically nothing of the mobile app is included in the desktop app, so nothing of the codebase could be reused. 
But I will look at this new method and if I like it I may update this project!
